# Generated by Django 5.0.6 on 2024-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_user_favorito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabalho",
            name="nome",
            field=models.CharField(max_length=30),
        ),
    ]
