# Generated by Django 5.0.6 on 2024-12-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_trabalho_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passage_id",
        ),
    ]
