# Generated by Django 5.0.6 on 2024-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_user_passage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="publicacao",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
